# Use postgres/example user/password credentials

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./reservation-backend
    image: backend
    restart: always
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
    - ./reservation-backend:/app
    depends_on:
      - db

  # frontend:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./reservation-frontend
  #   image: parcial-2-frontend
  #   restart: "no"
  #   container_name: parcial-2-frontend
  #   ports:
  #     - "3000:3000"

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: reservation
    volumes:
      - postgres_data:/var/lib/postgresql


  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  postgres_data:

